@use('AbeTwoThree\LaravelTsPublish\Facades\JsEmitter')
@use('AbeTwoThree\LaravelTsPublish\Facades\TsTypeString')
/* eslint-disable */
// biome-ignore lint: disable
// oxlint-disable
// --- ---
// This file is auto-generated by laravel-ts-publish. Do not edit this file directly.
// Read more: https://github.com/abetwothree/laravel-ts-publish
export {}
@if(count($externalTypeImports) > 0)

@foreach ($externalTypeImports as $path => $types)
import type { {{ implode(', ', $types) }} } from '{{ $path }}';
@endforeach
@endif

/* prettier-ignore */
declare global {
@foreach ($groupedModels as $namespace => $transformers)
@if ($transformers->count() > 0)
    export namespace {{ $namespace }} {
@foreach ($transformers as $transformer)
@if($transformer->description)
{!! JsEmitter::formatJsDoc($transformer->description, 8) !!}
@endif
        export interface {{ $transformer->modelName }}{!! count($transformer->tsExtends) > 0 ? ' extends '.implode(', ', $transformer->tsExtends) : '' !!} {
@if (count($transformer->columns) > 0)
            // Columns
@foreach($transformer->columns as $name => $column)
@if($column['description'])
{!! JsEmitter::formatJsDoc($column['description'], 12) !!}
@endif
            {!! JsEmitter::validJsObjectKey($name) !!}{{ $column['optional'] ? '?' : '' }}: {!! TsTypeString::qualifyGlobalType($column['type'], $globalTypesByNamespace, $namespace, $globalAliasMap) !!};
@endforeach
@endif
@if (count($transformer->mutators) > 0 || count($transformer->appends) > 0)
            // Mutators
@foreach($transformer->mutators as $name => $mutator)
@if($mutator['description'])
{!! JsEmitter::formatJsDoc($mutator['description'], 12) !!}
@endif
            {!! JsEmitter::validJsObjectKey($name) !!}{{ $mutator['optional'] ? '?' : '' }}: {!! TsTypeString::qualifyGlobalType($mutator['type'], $globalTypesByNamespace, $namespace, $globalAliasMap) !!};
@endforeach
@foreach($transformer->appends as $name => $append)
@if($append['description'])
{!! JsEmitter::formatJsDoc($append['description'], 12) !!}
@endif
            {!! JsEmitter::validJsObjectKey($name) !!}{{ $append['optional'] ? '?' : '' }}: {!! TsTypeString::qualifyGlobalType($append['type'], $globalTypesByNamespace, $namespace, $globalAliasMap) !!};
@endforeach
@endif
@if (count($transformer->relations) > 0)
            // Relations
@foreach($transformer->relations as $name => $relation)
@if($relation['description'])
{!! JsEmitter::formatJsDoc($relation['description'], 12) !!}
@endif
            {!! JsEmitter::validJsObjectKey($name) !!}: {!! TsTypeString::qualifyGlobalType($relation['type'], $globalTypesByNamespace, $namespace, $globalAliasMap) !!};
            {!! JsEmitter::validJsObjectKey($name.'_count') !!}: number;
            {!! JsEmitter::validJsObjectKey($name.'_exists') !!}: boolean;
@endforeach
@endif
        }
@endforeach
    }
@endif
@endforeach
@foreach ($groupedEnums as $namespace => $transformers)
@if ($transformers->count() > 0)
    export namespace {{ $namespace }} {
@foreach ($transformers as $transformer)
@if($transformer->description)
{!! JsEmitter::formatJsDoc($transformer->description, 8) !!}
@endif
        export interface {{ $transformer->enumName }}
        {
@foreach($transformer->cases as $case)
@if($case['description'])
{!! JsEmitter::formatJsDoc($case['description'], 12) !!}
@endif
            {!! JsEmitter::validJsObjectKey($case['name']) !!}: {!! JsEmitter::toJsLiteral($case['value']) !!},
@endforeach
        }
        export type {{ $transformer->enumName }}Type = {!! implode(' | ', $transformer->caseTypes) !!};
@if($transformer->backed)
        export type {{ $transformer->enumName }}Kind = {!! implode(' | ', $transformer->caseKinds) !!};
@endif
@if(!$loop->last)

@endif
@endforeach
    }
@endif
@endforeach
@foreach ($groupedResources as $namespace => $transformers)
@if ($transformers->count() > 0)
    export namespace {{ $namespace }} {
@foreach ($transformers as $transformer)
@if($transformer->description)
{!! JsEmitter::formatJsDoc($transformer->description, 8) !!}
@endif
@if($transformer->typeAlias !== null)
        export type {{ $transformer->resourceName }} = {!! TsTypeString::qualifyGlobalType($transformer->typeAlias, $globalTypesByNamespace, $namespace, $globalAliasMap) !!};
@else
        export interface {{ $transformer->resourceName }}{!! count($transformer->tsExtends) > 0 ? ' extends '.implode(', ', $transformer->tsExtends) : '' !!} {
@foreach ($transformer->properties as $name => $property)
@if($property['description'])
{!! JsEmitter::formatJsDoc($property['description'], 12) !!}
@endif
            {!! JsEmitter::validJsObjectKey($name, allowIndexSignature: true) !!}{!! $property['optional'] ? '?' : '' !!}: {!! TsTypeString::qualifyGlobalType(TsTypeString::rewriteAsEnumToType($property['type'], $transformer->globalEnumConstMap()), $globalTypesByNamespace, $namespace, $globalAliasMap) !!};
@endforeach
        }
@endif
@endforeach
    }
@endif
@endforeach
@foreach ($groupedFormRequests as $namespace => $transformers)
@if ($transformers->count() > 0)
    export namespace {{ $namespace }} {
@foreach ($transformers as $transformer)
@if($transformer->isDynamic)
        export type {{ $transformer->typeName }} = Record<string, unknown>;
@else
        export interface {{ $transformer->typeName }}{!! count($transformer->tsExtends) > 0 ? ' extends '.implode(', ', $transformer->tsExtends) : '' !!} {
@foreach ($transformer->fields as $field)
@if(!$field['isProhibited'])
@php
$fieldType = $field['tsType'];
if ($field['isNullable']) {
    $fieldType .= ' | null';
}
$optional = ! $field['isRequired'] ? '?' : '';
@endphp
            {!! JsEmitter::validJsObjectKey($field['fieldPath']) !!}{{ $optional }}: {!! $fieldType !!};
@endif
@endforeach
        }
@endif
@endforeach
    }
@endif
@endforeach
@foreach ($groupedBroadcastEvents as $namespace => $transformers)
@if ($transformers->count() > 0)
    export namespace {{ $namespace }} {
@foreach ($transformers as $transformer)
        export interface {{ $transformer->eventName }}{!! count($transformer->tsExtends) > 0 ? ' extends '.implode(', ', $transformer->tsExtends) : '' !!} {
@foreach ($transformer->properties as $name => $prop)
@php
$optional = $prop['optional'] ? '?' : '';
@endphp
            {!! JsEmitter::validJsObjectKey($name) !!}{{ $optional }}: {!! TsTypeString::qualifyGlobalType($prop['type'], $globalTypesByNamespace, $namespace, $transformer->globalTypeReferenceMap()) !!};
@endforeach
        }
@endforeach
    }
@endif
@endforeach
}
